### PR TITLE
ENH update tag line

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
Note that merging this PR will remove python 2.7 from the build matrix and result in no python 2.7 versions going forward. cc @esheldon 

Old versions already shipped will remain.

**Comment by esheldon** [comment]
python 2.7 is still supported, and is run in travis on  the main repo. I did remove it temporarily while testing but it is back in there.

**Comment by esheldon** [comment]
I won't remove 2.7 until version 2.0 of ngmix is released

**Comment by beckermr** [comment]
Conda forge deprecated aupport. If you want 1.3.8 on py27, we’ll have to push a special build

**Comment by esheldon** [comment]
OK, its fine to drop 2.7.  Thanks.

**Pull request merged**
